baseURL = "http://gottalottasoul.com/"
languageCode = "en-us"
theme = "hugo-theme-casper"
title = "Blake's R Blog"

[params]
author = "Blake Abbenante"
authorlocation = "Boston, MA"
authorwebsite = "http://abbenante.com"
authorbio = "Analytics guy"
description = "My not-so-polished blog about R"
googleAnalyticsUserID = "UA-4974577-3"
githubName = "gottalottasoul"
twitterName = "gottalottasoul"
hideHUGOSupport = true
